# Generated by Django 3.2 on 2021-04-23 09:57

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pug',
            fields=[
                ('uuid', models.UUIDField(db_index=True, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(help_text='Holds the name of the Pug', max_length=128, verbose_name='Name')),
                ('owner', models.CharField(db_index=True, help_text='discord.Member.id', max_length=128, null=True, verbose_name='Owner')),
                ('players', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=128), blank=True, db_index=True, default=list, help_text='Array of discord.Member.id(s) that belong to this Pug', null=True, size=None)),
                ('guild', models.CharField(db_index=True, help_text='The discord.Guild.id that this pug was created in', max_length=128, verbose_name='Guild')),
                ('text_channel', models.CharField(db_index=True, help_text='The discord.TextChannel.id that this pug was created in', max_length=128, verbose_name='Text Channel')),
                ('max_size', models.PositiveIntegerField(default=10, help_text='Holds the max size of this Pug', verbose_name='Max Size')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Open'), (2, 'Started'), (3, 'Closed')], default=1, help_text='Status of this Pug', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Pug',
                'verbose_name_plural': 'Pugs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('uuid', models.UUIDField(db_index=True, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(help_text='Name of the Team', max_length=128, verbose_name='Name')),
                ('captain', models.CharField(db_index=True, help_text='discord.Member.id', max_length=128, null=True, verbose_name='Captain')),
                ('players', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=128), blank=True, db_index=True, default=list, help_text='Array of discord.Member.id(s) that belong to this Team', null=True, size=None)),
                ('voice_channel', models.CharField(db_index=True, help_text='The discord.VoiceChannel.id that this pug will use', max_length=128, verbose_name='Voice Channel')),
                ('pug', models.ForeignKey(help_text='Pug that this team belongs to', on_delete=django.db.models.deletion.CASCADE, to='pugs.pug', verbose_name='Pug')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['-created_at'],
            },
        ),
    ]
